services:
    pim_enrich.messenger.serializer.business_event:
        class: Akeneo\Tool\Bundle\MessengerBundle\Serialization\JsonSerializer
        arguments:
            - !tagged pim_enrich.messenger.normalizer.business_event

    Akeneo\Pim\Enrichment\Bundle\Message\ProductUpdatedNormalizer:
        tags: [pim_enrich.messenger.normalizer.business_event]
